### ISSUE TITLE
veraPDF validation fails for LMI-report-cls and LMI-body-dev

### ISSUE THREAD

**Issue by jborbely** [apmp-dxfg/pdfa3-documents#3]
For [LMI-report-cls](https://github.com/apmp-dxfg/pdfa3-documents/tree/main/LMI-report-cls), after running `pdflatex ex_report.tex`,  veraPDF fails to validate (PDF/A-3B validation profile) the built PDF file with the following reason

<img width="100%" alt="image" src="https://github.com/apmp-dxfg/pdfa3-documents/assets/4319367/0e0b61e4-5aa0-4c76-ba6a-8a5374cf2e61">

Same validation error on the PDF for [LMI-body-dev](https://github.com/apmp-dxfg/pdfa3-documents/tree/main/LMI-body-dev).

Building the PDF in [LMI-title-dev](https://github.com/apmp-dxfg/pdfa3-documents/tree/main/LMI-title-dev), PDFs in [minimal](https://github.com/apmp-dxfg/pdfa3-documents/tree/main/minimal), and the PDF in [minimal-xmp](https://github.com/apmp-dxfg/pdfa3-documents/tree/main/minimal-xmp) pass veraPDF validation.

**Comment by BlairDHall** [comment]
Well spotted. I think I have fixed it now.

**Comment by jborbely** [comment]
Yes, 4065b45eea50855fbaff904acfa94f5aaa183ad2 fixed it.
